<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '产品中心';
$typeArr[3] = '大倾角皮带输送机';
$typeArr[4] = 'Ⅱ带式输送机';
$typeArr[5] = '型移动式胶带输送机';
$typeArr[6] = '移动式皮带机';
$typeArr[7] = '矿用型胶带输送机';
$typeArr[8] = '型链式输送机';
$typeArr[9] = 'TD75型胶带输送机';
$typeArr[10] = '伸缩带式输送机';
$typeArr[11] = '成功案例';
$typeArr[12] = '新闻中心';
$typeArr[13] = '行业新闻';
$typeArr[14] = '公司新闻';
$typeArr[15] = '网站公告';
$typeArr[16] = '售后服务';
$typeArr[17] = '人才招聘';
$typeArr[18] = '在线留言';
$typeArr[19] = '联系我们';
?>