<?php
$z[0]=Array("field","",348,367);
$z[0][4]['name']="title";
$z[1]=Array("global","",368,394);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1324,1361);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1587,1616);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1816,1837);
$z[4][4]['name']="content";
$z[5]=Array("include","",1863,1902);
$z[5][4]['filename']="footer_m.htm";

?>