<li class="news-li[field:global name=autoindex/]"> <a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" width="200" height="150" alt="[field:title/]"/></a>
        <div class="news-right"> <span>[field:pubdate function="MyDate('Y/m/d',@me)"/]</span>
          <h2><a href="[field:arcurl/]" title="">[field:title/]</a></h2>
          <div>[field:infos/]...</div>
        </div>
      </li>