<?php
$z[0]=Array("field","",345,364);
$z[0][4]['name']="title";
$z[1]=Array("global","",365,391);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1321,1358);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1584,1613);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n		<li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n		",1873,2023);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[5]=Array("field","",2091,2110);
$z[5][4]['name']="title";
$z[6]=Array("field","",2148,2166);
$z[6][4]['name']="body";
$z[7]=Array("prenext","",2183,2211);
$z[7][4]['get']="preimg";
$z[8]=Array("prenext","",2217,2246);
$z[8][4]['get']="nextimg";
$z[9]=Array("type","<a href=\"list.php?tid=[field:id/]\" title=\"返回列表\" class=\"back\">返回列表</a>",2251,2376);
$z[9][4]['typeid']="0";
$z[9][4]['row']="1";
$z[10]=Array("include","",2387,2426);
$z[10][4]['filename']="footer_m.htm";

?>