<?php
$z[0]=Array("field","",345,364);
$z[0][4]['name']="title";
$z[1]=Array("global","",365,391);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1321,1358);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1584,1613);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n		<li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"iconfont class-down\">&#xe608;</span>\r\n          <dl>\r\n          </dl>\r\n        </li>\r\n		",1873,2126);
$z[4][4]['typeid']="2";
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[5]=Array("field","",2223,2242);
$z[5][4]['name']="title";
$z[6]=Array("productimagelist","\r\n	  <center>\r\n        <img src=\"[field:imgsrc/]\" />\r\n      </center>\r\n	  <p style=\"height:10px\"></p>\r\n	  ",2252,2405);
$z[7]=Array("field","",2413,2431);
$z[7][4]['name']="body";
$z[8]=Array("prenext","",2481,2509);
$z[8][4]['get']="preimg";
$z[9]=Array("prenext","",2515,2544);
$z[9][4]['get']="nextimg";
$z[10]=Array("type","<a href=\"list.php?tid=[field:id/]\" title=\"返回列表\" class=\"back\">返回列表</a>",2550,2675);
$z[10][4]['typeid']="0";
$z[10][4]['row']="1";
$z[11]=Array("include","",2696,2735);
$z[11][4]['filename']="footer_m.htm";

?>