<?php
$z[0]=Array("field","",348,367);
$z[0][4]['name']="title";
$z[1]=Array("global","",368,394);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1324,1361);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1587,1616);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n		<li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"iconfont class-down\">&#xe608;</span>\r\n          <dl>\r\n          </dl>\r\n        </li>\r\n		",1876,2129);
$z[4][4]['typeid']="2";
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[5]=Array("field","",2226,2245);
$z[5][4]['name']="title";
$z[6]=Array("productimagelist","\r\n	  <center>\r\n        <img src=\"[field:imgsrc/]\" />\r\n      </center>\r\n	  <p style=\"height:10px\"></p>\r\n	  ",2255,2408);
$z[7]=Array("field","",2416,2434);
$z[7][4]['name']="body";
$z[8]=Array("prenext","",2484,2512);
$z[8][4]['get']="preimg";
$z[9]=Array("prenext","",2518,2547);
$z[9][4]['get']="nextimg";
$z[10]=Array("type","<a href=\"list.php?tid=[field:id/]\" title=\"返回列表\" class=\"back\">返回列表</a>",2553,2678);
$z[10][4]['typeid']="0";
$z[10][4]['row']="1";
$z[11]=Array("include","",2699,2738);
$z[11][4]['filename']="footer_m.htm";

?>