<?php
$z[0]=Array("channel","\r\n  <span>|</span><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a>\r\n  ",94,247);
$z[0][4]['row']="10";
$z[0][4]['type']="top";
$z[0][4]['col']="1";
$z[1]=Array("flink","\r\n    [field:link /] ",498,590);
$z[1][4]['row']="24";
$z[1][4]['type']="text";
$z[1][4]['titlelen']="24";
$z[1][4]['typeid']="0";
$z[2]=Array("global","",712,738);
$z[2][4]['name']="cfg_banquan";
$z[3]=Array("global","",915,939);
$z[3][4]['name']="cfg_beian";

?>