<?php
$z[0]=Array("global","",376,402);
$z[0][4]['name']="cfg_dianhua";
$z[1]=Array("global","",513,538);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",1711,1737);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",1797,1823);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("field","(@me==\"\")? @me=\"   class='on'  \":@me=\"\";",1902,1992);
$z[4][4]['name']="typeid";
$z[4][4]['runphp']="yes";
$z[5]=Array("channel","\r\n		<li> <a href=\"[field:typeurl/]\" title=\"[field:typename/]\"> <span>[field:typename/]</span></a> </li>\r\n		",2033,2288);
$z[5][4]['row']="10";
$z[5][4]['type']="top";
$z[5][4]['col']="1";
$z[5][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='on'><span>~typename~</span></a></li>";

?>