<?php
$z[0]=Array("global","",345,371);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",424,454);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",491,518);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1367,1404);
$z[3][4]['filename']="head_m.htm";
$z[4]=Array("type","<span>[field:typename/]</span>",2174,2238);
$z[4][4]['typeid']="2";
$z[5]=Array("channel","\r\n	  <li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\"> <img src=\"/m/skin/images/chanpin/chanpin[field:global name=autoindex/].jpg\" alt=\"[field:typename/]\"/> <span>[field:typename/]</span> </a> </li>\r\n	  ",2309,2588);
$z[5][4]['typeid']="2";
$z[5][4]['type']="son";
$z[5][4]['row']="3";
$z[6]=Array("type","<span>[field:typename/]</span>EWS</p>\r\n      </div>\r\n      <a href=\"list.php?tid=[field:id/]\" title=\"更多\">>>更多</a> ",2691,2848);
$z[6][4]['typeid']="12";
$z[7]=Array("arclist","\r\n	<div class=\"inews\"> \r\n	<a href=\"view.php?aid=[field:id/]\" class=\"news-img\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"/></a>\r\n      <p>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</p>\r\n      <h3><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n      <div>[field:infos/]...</div>\r\n    </div>\r\n	",2863,3284);
$z[7][4]['row']="2";
$z[7][4]['typeid']="12";
$z[7][4]['titlelen']="60";
$z[8]=Array("type"," <span>[field:typename/]</span>",3310,3375);
$z[8][4]['typeid']="2";
$z[9]=Array("arclist","\r\n	  <li> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\"/> <span>[field:title/]</span> </a> </li>\r\n	  ",3440,3662);
$z[9][4]['row']="4";
$z[9][4]['typeid']="2";
$z[9][4]['titlelen']="60";
$z[10]=Array("type","<a href=\"list.php?tid=[field:id/]\" title=\"点击查看更多\" class=\"imore\">点击查看更多</a>",3679,3811);
$z[10][4]['typeid']="2";
$z[11]=Array("arclist","\r\n	  <a href=\"\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" width=\"175\" height=\"131\"/></a>\r\n	  ",3873,4056);
$z[11][4]['row']="3";
$z[11][4]['typeid']="11";
$z[11][4]['titlelen']="60";
$z[12]=Array("include","",4230,4269);
$z[12][4]['filename']="footer_m.htm";

?>