<?php
$z[0]=Array("field","",298,317);
$z[0][4]['name']="title";
$z[1]=Array("global","",318,344);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1785,1820);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n			<li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n			",2845,3084);
$z[3][4]['row']="10";
$z[3][4]['typeid']="2";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li class='on'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[4]=Array("global","",3366,3390);
$z[4][4]['name']="cfg_dizhi";
$z[5]=Array("global","",3417,3443);
$z[5][4]['name']="cfg_dianhua";
$z[6]=Array("global","",3541,3567);
$z[6][4]['name']="cfg_dianhua";
$z[7]=Array("field","",3682,3711);
$z[7][4]['name']="typename";
$z[8]=Array("field","",3746,3775);
$z[8][4]['name']="position";
$z[9]=Array("field","",3834,3855);
$z[9][4]['name']="content";

?>