<?php
$z[0]=Array("field","",345,364);
$z[0][4]['name']="title";
$z[1]=Array("global","",365,391);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1321,1358);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1584,1613);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n		<li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n		",1873,2023);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[5]=Array("list","\r\n	  <li class=\"news1\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><span>[field:title/]</span><span>[field:pubdate function=\"MyDate('Y/m/d',@me)\"/]</span></a> </li>\r\n	  ",2128,2363);
$z[5][4]['pagesize']="10";
$z[5][4]['infolen']="150";
$z[6]=Array("pagelist","",2422,2481);
$z[6][4]['istitem']="index,pre,next,end,";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2520,2559);
$z[7][4]['filename']="footer_m.htm";

?>