<?php
$z[0]=Array("field","",348,367);
$z[0][4]['name']="title";
$z[1]=Array("global","",368,394);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1324,1361);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1587,1616);
$z[3][4]['name']="typename";
$z[4]=Array("list","\r\n	  <li> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\"></a>\r\n        <h1><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">[field:title/]</a></h1>\r\n        <div>[field:infos/]...</div>\r\n      </li>\r\n	  ",1831,2118);
$z[4][4]['pagesize']="5";
$z[5]=Array("pagelist","",2163,2222);
$z[5][4]['istitem']="index,pre,next,end,";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",2268,2307);
$z[6][4]['filename']="footer_m.htm";

?>