<?php
$z[0]=Array("field","",301,320);
$z[0][4]['name']="title";
$z[1]=Array("global","",321,347);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1788,1823);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n			<li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n			",2841,3080);
$z[3][4]['row']="10";
$z[3][4]['typeid']="2";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li class='on'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[4]=Array("global","",3362,3386);
$z[4][4]['name']="cfg_dizhi";
$z[5]=Array("global","",3413,3439);
$z[5][4]['name']="cfg_dianhua";
$z[6]=Array("global","",3534,3560);
$z[6][4]['name']="cfg_dianhua";
$z[7]=Array("field","",3675,3704);
$z[7][4]['name']="typename";
$z[8]=Array("field","",3739,3768);
$z[8][4]['name']="position";
$z[9]=Array("list","\r\n		  <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"pro-img\"><img src=\"[field:picname/]\" width=\"229\" height=\"172\" alt=\"[field:title/]\" /></a> <span class=\"zoom\"></span>\r\n            <p><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></p>\r\n          </li>\r\n		  ",3870,4200);
$z[9][4]['pagesize']="9";
$z[10]=Array("pagelist","",4245,4304);
$z[10][4]['istitem']="index,pre,next,end,";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",4356,4393);
$z[11][4]['filename']="footer.htm";

?>