<?php
$z[0]=Array("field","",298,317);
$z[0][4]['name']="title";
$z[1]=Array("global","",318,344);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1785,1820);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n			<li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n			",2845,2996);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[4]=Array("global","",3278,3302);
$z[4][4]['name']="cfg_dizhi";
$z[5]=Array("global","",3329,3355);
$z[5][4]['name']="cfg_dianhua";
$z[6]=Array("global","",3453,3479);
$z[6][4]['name']="cfg_dianhua";
$z[7]=Array("field","",3594,3623);
$z[7][4]['name']="typename";
$z[8]=Array("field","",3658,3687);
$z[8][4]['name']="position";
$z[9]=Array("list","\r\n		  <li > <a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a> <span>[field:pubdate function=\"MyDate('Y/m/d',@me)\"/]</span> </li>\r\n		  ",3775,3977);
$z[9][4]['pagesize']="9";
$z[9][4]['infolen']="150";
$z[10]=Array("pagelist","",4022,4081);
$z[10][4]['istitem']="index,pre,next,end,";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",4133,4170);
$z[11][4]['filename']="footer.htm";

?>