<?php
$z[0]=Array("field","",301,320);
$z[0][4]['name']="title";
$z[1]=Array("global","",321,347);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1788,1823);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n			<li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n			",2841,2992);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[4]=Array("global","",3274,3298);
$z[4][4]['name']="cfg_dizhi";
$z[5]=Array("global","",3325,3351);
$z[5][4]['name']="cfg_dianhua";
$z[6]=Array("global","",3446,3472);
$z[6][4]['name']="cfg_dianhua";
$z[7]=Array("field","",3587,3616);
$z[7][4]['name']="typename";
$z[8]=Array("field","",3651,3680);
$z[8][4]['name']="position";
$z[9]=Array("list","\r\n		  <li > <a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a> <span>[field:pubdate function=\"MyDate('Y/m/d',@me)\"/]</span> </li>\r\n		  ",3768,3970);
$z[9][4]['pagesize']="9";
$z[9][4]['infolen']="150";
$z[10]=Array("pagelist","",4015,4074);
$z[10][4]['istitem']="index,pre,next,end,";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",4126,4163);
$z[11][4]['filename']="footer.htm";

?>