<?php
$z[0]=Array("field","",348,367);
$z[0][4]['name']="title";
$z[1]=Array("global","",368,394);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1324,1361);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1587,1616);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n		<li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n		",1876,2026);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[5]=Array("list","\r\n	  <li class=\"news1\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><span>[field:title/]</span><span>[field:pubdate function=\"MyDate('Y/m/d',@me)\"/]</span></a> </li>\r\n	  ",2131,2366);
$z[5][4]['pagesize']="10";
$z[5][4]['infolen']="150";
$z[6]=Array("pagelist","",2425,2484);
$z[6][4]['istitem']="index,pre,next,end,";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2523,2562);
$z[7][4]['filename']="footer_m.htm";

?>