<?php
$z[0]=Array("field","",301,320);
$z[0][4]['name']="title";
$z[1]=Array("global","",321,347);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1788,1823);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n			<li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n			",2841,3080);
$z[3][4]['row']="10";
$z[3][4]['typeid']="2";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li class='on'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[4]=Array("global","",3362,3386);
$z[4][4]['name']="cfg_dizhi";
$z[5]=Array("global","",3413,3439);
$z[5][4]['name']="cfg_dianhua";
$z[6]=Array("global","",3534,3560);
$z[6][4]['name']="cfg_dianhua";
$z[7]=Array("field","",3675,3704);
$z[7][4]['name']="typename";
$z[8]=Array("field","",3739,3768);
$z[8][4]['name']="position";
$z[9]=Array("include","",5648,5685);
$z[9][4]['filename']="footer.htm";

?>