<?php
$z[0]=Array("global","",308,334);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",1775,1810);
$z[1][4]['filename']="head.htm";
$z[2]=Array("global","",2799,2823);
$z[2][4]['name']="cfg_dizhi";
$z[3]=Array("global","",2850,2876);
$z[3][4]['name']="cfg_dianhua";
$z[4]=Array("global","",2974,3000);
$z[4][4]['name']="cfg_dianhua";
$z[5]=Array("field","",3115,3144);
$z[5][4]['name']="typename";
$z[6]=Array("list","\r\n		  <li > <a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a> <span>[field:pubdate function=\"MyDate('Y/m/d',@me)\"/]</span> </li>\r\n		  ",3283,3485);
$z[6][4]['pagesize']="9";
$z[6][4]['infolen']="150";
$z[7]=Array("pagelist","",3530,3589);
$z[7][4]['istitem']="index,pre,next,end,";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",3641,3678);
$z[8][4]['filename']="footer.htm";

?>